<?php

namespace app\example\types\migrations;

use extpoint\yii2\base\Migration;

class M170418035813_Example_types_players extends Migration
{
    public function up() {
        $this->createTable('example_types_players', [
            'id' => $this->primaryKey(),
            'name' => $this->string()->notNull(),
            'email' => $this->string()->notNull(),
        ]);
        
        $nicks = [
            'Bad Bunny',
            'Willow Dragon',
            'SmartieQuest',
            'Chip Queen',
            'Reed Lady',
            'DriftDetector',
            'Street Squirrel',
            'White Snare',
            'Night Magnet',
            'RoarSweetie',
            'Poppy Coffee',
            'Polar Bee',
            'Racy Lion',
            'Light Lion',
            'Subzero Taffy',
            'Chasm Face',
            'Mint Ness',
            'Pixie Soldier',
            'DuckDuck',
            'Mum Mary',
            'LifeRobber',
            'Killah Goose',
            'Daffy Girl',
            'Eerie Mizzen',
            'Acid Gosling',
            'Fennel Dove',
            'Jelly Camber',
            'Arsenic Coo',
            'Cool Iris',
            'Toy Dogwatch',
            'Roller Turtle',
            'Marigold Loot',
            'Vicious Street',
            'Alley Frog',
            'Moon Solitaire',
            'New York Winder',
            'Gullyway',
            'Snow Cream',
            'Trash Sling',
            'Romance Guppy',
            'SunVolt',
            'Green Scavenger',
            'Natural Gold',
            'SpellTansy',
            'Lava Nibbler',
            'Phoenix Tetra',
            'TulipCake',
            'Devil Blade',
            'Fire Fish',
            'Sienna Princess',
            'Twin Blaze',
            'Back Bett',
            'Bug Fire',
            'NoiseFire',
            'Koi Diva',
            'Widow Curio',
            'TrixiePhany',
            'Ember Rope',
            'Pink Hopper',
            'BlacKitten',
            'Congo Wire',
            'Betty Cricket',
            'Club Nola',
            'Impulsive Flower',
            'Dahlia Bumble',
            'Devil Chick',
            'Darling Peacock',
            'Reno Monarch',
            'Fire Feline',
            'Flame OUT',
            'Spooky Yellowjacket',
            'Nutmeg Riot',
            'RedMouth',
            'VenusLion',
            'NemesisX',
            'BloodEater',
            'Lunar Treat',
            'Feral Mayhem',
            'Terror Master',
            'Spunky Comet',
            'Fiend Oblivion',
            'Green Ghost',
            'Darkside Orbit',
            'Twinkle Cutlass',
            'Electric Saturn',
            'Metal Star',
            'Pearl Girl',
            'CoB@lt',
            'LunaStar',
            'Diamond Gamer',
            'Star Sword',
            'Cupid Dust',
            'Winter Bite',
            'Sass Burst',
            'MicroStar',
            'Fire Bite',
            'Mud Eye',
            'Starshine',
            'StormCake',
            'Cosmic Presence',
            'Digital Equinox',
            'Twister Hero',
            'Star Scratch',
            'RetroMirage',
            'Black Firefly',
            'Dakota Bliss',
            'Steel Solstice',
            'Blackfire',
            'Texas Butterfly',
            'Delirious Supernova',
            'Blizzard Vixen',
            'Geneva Cuffs',
            'Miss Twilight',
            'CirrusFlash',
            'Paris Boost',
            'StarZen',
            'PepperBurst',
            'London Fox',
            'Demo Zero',
            'Voodoo Cyclone',
            'Tokyo Dream',
            'Lucky Aurora',
            'Twisty Dew',
            'Dallas Burn',
            'Bang Shift',
            'Petite Flurry',
            'Nueva Nova',
            'Ginger Chaos',
            'Ship Whip',
            'Shady Prairie',
            'Murder Matter',
            'CloudFrenzy',
            'Milan Call Back',
            'FireBerry',
            'Pink Stream',
            'Roma Kabuki',
            'Light Despair',
            'SunnySnap',
            'Austin Shamrock',
            'Miss Nova',
            'Frosty Sunshine',
            'Athens Fire',
            'Parallax Sugar',
            'Aqua Monsoon',
            'Berlin Kamikaze',
            'Divine Quasar',
            'Breezy Mustang',
            'Bombay Shivers',
            'Virgo Moon',
            'Fuzzy Rainbow',
            'Kawaii Red',
            'Sun Leo',
            'Sand Whiskers',
            'California Goddess',
            'X-Dew',
            'Wiccan Thunder',
            'Cali Yacht',
            'Moon Radar',
            'Icy Avenger',
            'Lilac Lizard',
            'True Sweetness',
            'Snowflake Pixie',
            'Rosie Bird',
            'Dez North',
            'Jetta Talent',
            'Silver Rose',
            'Moon Laser',
            'Gold Bentley',
            'Daisy Stick',
            'Pixie Taze',
            'Pocket Mazda',
            'Black Fantastic',
            'Domino Combat',
            'Wild Tesla',
            'Sky Dahlia',
            'FLAK Angel',
            'Gothic Gucci',
            'Venom Petunia',
            'SWAT Honey',
            'Pepper Prada',
            'Lady Petal',
            'Helmet Destroyer',
            'Friday Ferrari',
            'Leaf Assassin',
            'Kevlar Wanted',
            'Dove Dolce',
            'Dance Bloom',
            'Orange Teflon',
            'Versace-Cat',
            'Lady Q',
            'Killer Grenade',
            'Bambi Benz'
        ];
        $mails = ['gmail.com', 'mail.ru', 'yahoo.com', 'ms.com', 'ya.ru'];

        $this->batchInsert('example_types_players', ['name', 'email'], array_map(function($nick) use ($mails) {
            return [
                'name' => $nick,
                'email' => strtolower(preg_replace('/[^0-9a-z-_]+/i', '', $nick)) . '@' . $mails[array_rand($mails)],
            ];
        }, $nicks));
    }

    public function down() {
        $this->dropTable('example_types_players');
    }
}
